# Workflow for updating Advent of Code badges

name: Update Badges

on:
  schedule:
    - cron: '52 7 1-26 12 *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                # clones your repo
          
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1998317
          session: ${{ secrets.AOC_SESSION }}
          year: 2022
      
      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
